from constants.files import (
    CITY_COORDS_FILENAME,
    WEATHER_HISTORY_FILENAME,
    WEATHER_HEAT_INDEX_FILENAME,
    HEAT_INDEX_PREDICTIONS_FILENAME,
    HEAT_INDEX_MODEL_FILENAME,
    HOURLY_HEAT_INDEX_FILENAME,
    HOURLY_HEAT_INDEX_JSON_FILENAME,
)
from pathlib import Path

REPO_ROOT: Path = Path(__file__).resolve().parent.parent
WEB_DIR: Path = REPO_ROOT / "web"

LOGS_DIR: Path = REPO_ROOT / "logs"
DATASET_DIR: Path = REPO_ROOT / "dataset"
DATASET_CLEAN_DIR: Path = DATASET_DIR / "clean"
DATASET_MISC_DIR: Path = DATASET_DIR / "misc"
DATASET_RAW_DIR: Path = DATASET_DIR / "raw"
DATASET_PREDICTION_DIR: Path = DATASET_DIR / "prediction"
PUBLIC_DATA_DIR: Path = REPO_ROOT / "public" / "data"
MODELS_DIR: Path = REPO_ROOT / "models"
WEB_PUBLIC_DIR: Path = WEB_DIR / "public"
WEB_PUBLIC_DATA_DIR: Path = WEB_PUBLIC_DIR / "data"

CITY_COORDS_FILE: Path = DATASET_CLEAN_DIR / CITY_COORDS_FILENAME
CITY_COORDS_RAW_FILE: Path = DATASET_RAW_DIR / CITY_COORDS_FILENAME
WEATHER_HISTORY_FILE: Path = DATASET_CLEAN_DIR / WEATHER_HISTORY_FILENAME
WEATHER_HISTORY_RAW_FILE: Path = DATASET_RAW_DIR / WEATHER_HISTORY_FILENAME
WEATHER_HEAT_INDEX_FILE: Path = DATASET_CLEAN_DIR / WEATHER_HEAT_INDEX_FILENAME
HEAT_INDEX_PREDICTIONS_FILE: Path = DATASET_PREDICTION_DIR / HEAT_INDEX_PREDICTIONS_FILENAME
HEAT_INDEX_MODEL_FILE: Path = MODELS_DIR / HEAT_INDEX_MODEL_FILENAME
HOURLY_HEAT_INDEX_FILE: Path = DATASET_CLEAN_DIR / HOURLY_HEAT_INDEX_FILENAME
HOURLY_HEAT_INDEX_PUBLIC_FILE: Path = WEB_PUBLIC_DATA_DIR / HOURLY_HEAT_INDEX_JSON_FILENAME

def ensure_dirs():
    for p in (
        LOGS_DIR,
        DATASET_CLEAN_DIR,
        DATASET_MISC_DIR,
        DATASET_RAW_DIR,
        DATASET_PREDICTION_DIR,
        PUBLIC_DATA_DIR,
        WEB_PUBLIC_DATA_DIR,
        MODELS_DIR,
    ):
        p.mkdir(parents=True, exist_ok=True)

__all__ = [
    "REPO_ROOT",
    "LOGS_DIR",
    "DATASET_DIR",
    "DATASET_CLEAN_DIR",
    "DATASET_MISC_DIR",
    "DATASET_RAW_DIR",
    "DATASET_PREDICTION_DIR",
    "PUBLIC_DATA_DIR",
    "WEB_PUBLIC_DIR",
    "WEB_PUBLIC_DATA_DIR",
    "MODELS_DIR",
    "CITY_COORDS_FILE",
    "CITY_COORDS_RAW_FILE",
    "WEATHER_HISTORY_FILE",
    "WEATHER_HISTORY_RAW_FILE",
    "WEATHER_HEAT_INDEX_FILE",
    "HOURLY_HEAT_INDEX_FILE",
    "HEAT_INDEX_PREDICTIONS_FILE",
    "HEAT_INDEX_MODEL_FILE",
    "HOURLY_HEAT_INDEX_PUBLIC_FILE",
    "ensure_dirs",
]
